### ISSUE TITLE
ACDD extension for related dataset

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#64]
We'll need to add that to the yaml file as:

```
related_dataset:
  maxOccurs: unbounded
  minOccurs: '0'
  relation_type:
    acdd_ext: related_dataset_relation_type
  id:
    acdd_ext: related_dataset_id
```

Then, the nc_to_mmd.py module must probably be updated.
